apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskserver-orgs
  namespace: taskserver
  labels:
    app: taskserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
