apiVersion: v1
kind: Service
metadata:
  name: taskserver-service-tcp
  namespace: taskserver
  labels:
    app: taskserver
spec:
  type: LoadBalancer
  ports:
    - name: taskserver-tcp
      port: 53589
      protocol: TCP
  selector:
    app: taskserver
