---
apiVersion: v1
kind: Namespace
metadata:
  name: certbot-nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certbot-nginx-pvc
  namespace: certbot-nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: certbot-nginx-deployment
  namespace: certbot-nginx
  labels:
    app: certbot-nginx
spec:
  selector:
    matchLabels:
      app: certbot-nginx
  template:
    metadata:
      labels:
        app: certbot-nginx
    spec:
      containers:
      - name: certbot-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: certbot-proof-volume
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: certbot-proof-volume
        hostPath:
          path: /home/joe/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-tcp
  namespace: certbot-nginx
  labels:
    app: certbot-nginx
spec:
  type: LoadBalancer
  ports:
    - name: certbot-nginx
      port: 80
      protocol: TCP
  selector:
    app: certbot-nginx
